# Generated by Django 5.0 on 2024-02-05 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("username", models.CharField(max_length=64)),
                ("outside", models.BooleanField(default=False)),
                ("master", models.BooleanField(default=False)),
                ("admin", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("confirmed", models.BooleanField(default=False)),
                ("data_join", models.DateField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place_name", models.CharField(default=None, max_length=32)),
                ("description", models.TextField(default=None)),
                ("creation_date", models.DateField(auto_now_add=True)),
                ("found_date", models.DateField()),
                ("lng", models.FloatField()),
                ("lat", models.FloatField()),
                ("type", models.CharField(max_length=64)),
                ("sortof", models.CharField(max_length=64)),
                ("period", models.CharField(max_length=64)),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
